In [19]:
import numpy as np

In [20]:
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [21]:
a2 = np.array([[1,2,3],[4,5,6]])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
a3 = np.array([
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]],
    [[10,11,12],
    [13,14,15],
    [16,17,18]]
    ])


a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [23]:
import pandas as pd

df = pd.DataFrame(a2)
df

0  1  2
0  1  2  3
1  4  5  6

In [24]:
ones= np.ones((2,3)) # fills the array with variations of ones
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [25]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

-use shift + tab into a function parentesis and jupyter will show a hint

In [26]:
range_array = np.arange(0, 10, 2) #start , finish, steps
range_array

array([0, 2, 4, 6, 8])

In [27]:
random_array = np.random.randint(0,10 , size=(3,4)) # randint = random of intiger , first the range of intigers then size of array
random_array

array([[9, 4, 3, 0],
       [3, 5, 0, 2],
       [3, 8, 1, 3]])

In [28]:
random_array.shape

(3, 4)

In [29]:
random2 = np.random.random((5,3))
random2

array([[0.52047748, 0.67887953, 0.72063265],
       [0.58201979, 0.53737323, 0.75861562],
       [0.10590761, 0.47360042, 0.18633234],
       [0.73691818, 0.21655035, 0.13521817],
       [0.32414101, 0.14967487, 0.22232139]])

In [30]:
np.random.seed(seed=0)#creates a instance where all the values of random are the same every time the cell is run , so you can share the exact data
random_array_3 = np.random.random((3,5))
random_array_3

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ],
       [0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152],
       [0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606]])

In [31]:
np.unique(range_array)# shows the unique values of an array

array([0, 2, 4, 6, 8])

In [32]:
a1[0]

1

In [33]:
a2[0]

array([1, 2, 3])

In [34]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
a3[:2, :2, :2] #first 2 values of each axis 

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [38]:
a4 = np.random.randint(10,size=(2, 3, 4, 5)) # 5 columns , 4 rows, 3 group, 2 dimension
a4

array([[[[3, 8, 2, 8, 4],
         [3, 0, 4, 3, 6],
         [9, 8, 0, 8, 5],
         [9, 0, 9, 6, 5]],

        [[3, 1, 8, 0, 4],
         [9, 6, 5, 7, 8],
         [8, 9, 2, 8, 6],
         [6, 9, 1, 6, 8]],

        [[8, 3, 2, 3, 6],
         [3, 6, 5, 7, 0],
         [8, 4, 6, 5, 8],
         [2, 3, 9, 7, 5]]],


       [[[3, 4, 5, 3, 3],
         [7, 9, 9, 9, 7],
         [3, 2, 3, 9, 7],
         [7, 5, 1, 2, 2]],

        [[8, 1, 5, 8, 4],
         [0, 2, 5, 5, 0],
         [8, 1, 1, 0, 3],
         [8, 8, 4, 4, 0]],

        [[9, 3, 7, 3, 2],
         [1, 1, 2, 1, 4],
         [2, 5, 5, 5, 2],
         [5, 7, 7, 6, 1]]]])

In [39]:
a4.shape , a4.ndim

((2, 3, 4, 5), 4)

In [40]:
# get the first 4 numbers of the inner most array
a4[:, :, :, :4] # the last is the inner part (columns)

array([[[[3, 8, 2, 8],
         [3, 0, 4, 3],
         [9, 8, 0, 8],
         [9, 0, 9, 6]],

        [[3, 1, 8, 0],
         [9, 6, 5, 7],
         [8, 9, 2, 8],
         [6, 9, 1, 6]],

        [[8, 3, 2, 3],
         [3, 6, 5, 7],
         [8, 4, 6, 5],
         [2, 3, 9, 7]]],


       [[[3, 4, 5, 3],
         [7, 9, 9, 9],
         [3, 2, 3, 9],
         [7, 5, 1, 2]],

        [[8, 1, 5, 8],
         [0, 2, 5, 5],
         [8, 1, 1, 0],
         [8, 8, 4, 4]],

        [[9, 3, 7, 3],
         [1, 1, 2, 1],
         [2, 5, 5, 5],
         [5, 7, 7, 6]]]])

In [48]:
a4[:1, :,:, :4] # change parameters 

array([[[[3, 8, 2, 8],
         [3, 0, 4, 3],
         [9, 8, 0, 8],
         [9, 0, 9, 6]],

        [[3, 1, 8, 0],
         [9, 6, 5, 7],
         [8, 9, 2, 8],
         [6, 9, 1, 6]],

        [[8, 3, 2, 3],
         [3, 6, 5, 7],
         [8, 4, 6, 5],
         [2, 3, 9, 7]]]])

In [51]:
a5 = np.random.randint(10,size=(3, 2, 4, 5))
a5

array([[[[4, 4, 5, 8, 8],
         [0, 1, 5, 9, 9],
         [6, 1, 4, 0, 4],
         [7, 7, 7, 6, 2]],

        [[6, 0, 2, 7, 7],
         [2, 6, 1, 3, 7],
         [0, 5, 4, 5, 5],
         [3, 8, 0, 1, 5]]],


       [[[4, 1, 5, 0, 6],
         [8, 8, 6, 3, 4],
         [4, 3, 6, 5, 9],
         [8, 1, 3, 8, 1]],

        [[5, 8, 0, 3, 7],
         [1, 7, 8, 0, 7],
         [5, 9, 9, 6, 8],
         [7, 5, 9, 1, 0]]],


       [[[0, 5, 6, 3, 6],
         [1, 7, 7, 0, 7],
         [6, 0, 4, 2, 7],
         [5, 2, 8, 5, 6]],

        [[6, 4, 1, 5, 4],
         [5, 5, 6, 3, 8],
         [1, 4, 2, 9, 7],
         [4, 1, 8, 2, 3]]]])

In [54]:
a6 = np.random.randint(10,size=(2, 3, 2, 4, 5))
a6

array([[[[[7, 0, 8, 1, 2],
          [8, 5, 8, 2, 1],
          [3, 5, 0, 2, 5],
          [8, 6, 2, 7, 7]],

         [[1, 8, 4, 9, 3],
          [3, 2, 9, 0, 4],
          [6, 4, 3, 2, 3],
          [1, 1, 2, 7, 2]]],


        [[[7, 0, 1, 8, 0],
          [5, 2, 8, 0, 4],
          [0, 3, 8, 1, 6],
          [4, 6, 9, 6, 4]],

         [[7, 2, 9, 8, 0],
          [8, 6, 2, 6, 9],
          [5, 3, 7, 8, 3],
          [8, 8, 9, 9, 4]]],


        [[[4, 1, 0, 7, 6],
          [2, 1, 0, 6, 1],
          [6, 7, 1, 5, 2],
          [0, 2, 6, 6, 3]],

         [[5, 4, 7, 3, 2],
          [6, 9, 1, 5, 1],
          [9, 3, 1, 0, 7],
          [3, 9, 6, 4, 4]]]],



       [[[[3, 5, 4, 4, 9],
          [0, 0, 9, 5, 0],
          [6, 3, 8, 9, 6],
          [2, 1, 7, 7, 6]],

         [[7, 5, 9, 8, 8],
          [1, 4, 6, 4, 2],
          [7, 8, 5, 7, 9],
          [9, 6, 9, 9, 3]]],


        [[[9, 3, 7, 2, 8],
          [1, 3, 2, 1, 7],
          [8, 7, 5, 7, 7],
          [1, 5, 6, 5, 8]],

